/** Bulgarian UI copy. Core returns codes; the UI looks the words up here. */
export const STRINGS = {
  appName: 'Белот',
  screens: {
    home: 'Белот',
    setup: 'Нова игра',
    table: 'Маса',
    history: 'История на мача',
    end: 'Край на мача',
    stats: 'Класация',
  },
  themes: {
    pub: { name: 'Кръчма', sub: 'бира и дим' },
    home: { name: 'Вкъщи', sub: 'ракия и салата' },
    casino: { name: 'Сукно', sub: 'класическа маса' },
    night: { name: 'Късна нощ', sub: 'последна поръчка' },
  },
  felts: { wood: 'Дърво', cloth: 'Сукно', check: 'Покривка', stone: 'Камък' },
  routeError: {
    title: 'Нещо се обърка.',
    home: 'Към началния екран',
  },
  /** Indexed by Seat: 0 North, 1 East, 2 South, 3 West. */
  seats: ['Север', 'Изток', 'Юг', 'Запад'],
  home: {
    subtitle: 'Записва обявите и точките, докато вие играете.',
    newGame: 'Нова игра',
    stats: 'Класация',
    theme: 'Тема',
    newPlayer: 'Нов играч',
    share: 'Сподели / Внос',
    players: 'Играчи',
    empty: 'Още няма регистрирани играчи.',
  },
  register: {
    titleNew: 'Нов играч',
    titleEdit: 'Редакция на играч',
    name: 'Име или прякор',
    icon: 'Смешна иконка',
    random: '🎲 Случайна',
    photo: 'Или качи снимка',
    cancel: 'Отказ',
    save: 'Запази',
    delete: 'Изтрий играча',
    // Not in the handoff (ADR 0010): shown instead of the delete button. See docs/Status.md.
    inMatch: 'Играчът е в текущия мач и не може да бъде изтрит.',
    errors: { empty: 'Въведете име.', duplicate: 'Вече има играч с това име.' },
  },
  setup: {
    back: '← Начало',
    title: 'Нова игра',
    hint: 'Изберете кой къде седи. Партньорите седят един срещу друг.',
    teamA: 'Ние',
    teamB: 'Вие',
    teamASeats: 'Север · Юг',
    teamBSeats: 'Изток · Запад',
    // Not in the handoff: accessible names for the team-name inputs. See docs/Status.md.
    teamAName: 'Име на отбора Север · Юг',
    teamBName: 'Име на отбора Изток · Запад',
    pickPlayer: 'Избери играч',
    series: 'Брой мачове',
    seriesOptions: [
      { value: 1, label: '1 мач' },
      { value: 3, label: '2 от 3' },
      { value: 5, label: '3 от 5' },
      { value: 7, label: '4 от 7' },
    ],
    hintTarget: (target: number) => `Всеки мач се играе до ${target} точки`,
    hintSeats: 'Изберете играч за всяко от 4-те места.',
    deal: 'Раздавай!',
    seatTitle: (seat: string) => `Място: ${seat}`,
    newPlayer: '+ Нов играч',
  },
  theme: { title: 'Атмосфера', themes: 'Тема', felts: 'Маса', done: 'Готово' },
} as const;
